name: CI

on:
  push:
    branches:
      - main  # Adjust branch name as needed
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: actions/setup-swift@v2
      with:
        swift-version: '5.5'  # Adjust Swift version as needed

    - name: Build and test
      run: |
        swift build
        swift test
^x
^X

